name: Auto-deploy mkdocs whenever a pull request is merged

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy-docs:
   name: Deploy Docs to GitHubIO
   runs-on: ubuntu-latest
   steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup environment for docs deployment
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install meatballs packages
      run: pip install -e .
    - name: Deploy documentation
      run: mkdocs gh-deploy --force
